ARG NESTCLI_VERSION="9.1.8"
ARG EXPOCLI_VERSION="6.1.0"

FROM mcr.microsoft.com/devcontainers/javascript-node:0-18

RUN npm i -g @nestjs/cli@${NESTCLI_VERSION}
RUN npm i -g expo-cli@${EXPOCLI_VERSION}
